### ISSUE TITLE
ca-on-ottawa.json - Not coming up on map - Incomplete coverage?

### ISSUE THREAD

**Issue by MAL315** [openaddresses/openaddresses#1003]
Hi,

http://data.openaddresses.io says the ca-on-ottawa source has incomplete coverage but when I look for my own address in the file it comes up, as well as other addresses. I'm not exactly sure how I could fix it so that it maps.. I've noticed the same thing for others like ca-on-toronto and ca-qc-montreal.

My end goal is to be able to search in OSMand+ by address instead of address range but it hasn't updated yet and it's been over 3 weeks.

Any ideas how to fix this?

Thanks,
Marc

**Comment by geobrando** [comment]
Hey @MAL315 

It looks like Ottawa address points are being rendered at openaddresses.io.  If you're talking about the extent map at [data.openaddresses.io](http://data.openaddresses.io), it's required that 1 of 3 tags is present in the coverage object in order for the extent to be rendered.  See the requirements [here](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#coverage-object) which also has examples.

In terms of age of the data, the source data are not frequently recached and processed.  I would say 3 weeks is not terribly old as the source data are not expected to change that often.  @iandees might be able to say more.

**Comment by MAL315** [comment]
1 - I guess US Census wouldn't work since it's in Canada.

2 - The ISO-3166-2 seems to be for countries and states but I'd like to get a city to map, can I still use ISO-3166-2? Something like: "ISO 3166": {"alpha2": "CA-ON", "state": "Ontario", "country": "Canada"} and it'll pick up the city under the coverage section? 

3 - "Geometry with Polygon or MultiPolygon type unprojected" depends entirely on how the city/province is providing the mapping info (not something I can control - unless they provide different files)?

(https://github.com/openaddresses/openaddresses/blob/master/sources/ca-on-ottawa.json)

Thanks again,
Marc

**Comment by geobrando** [comment]
@MAL315 Yeah, the system in place for rendering sources on that map is not really optimized for many non-US geographies.  I think that option #3 was meant to be a workaround because of that.

The GeoJSON doesn't necessarily have to be provided by the city. If you care that much, it shouldn't be too difficult to find shapefiles of these cities and convert to GeoJSON using [ogr2ogr](http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/) or even some desktop GIS programs.

**Comment by MAL315** [comment]
I'm not too too worried about it but I was just wondering if that was affecting the data from coming up in OpenStreetMap. If it's purely just mapping at data.openaddresses.io (for visual appeal) then I'll let it go :) and I'll just wait for OSM to update eventually.

Thanks for your help.

**Comment by geobrando** [comment]
@MAL315 Oh, now I'm confused.  Were you under the impression that Openaddresses data is being funneled into OSM?  I was wondering why you mentioned OSMand+. My understanding is that OA was created at least partially because there are license restrictions preventing importing many data into OSM.  There's not currently any relationship between OA and OSM, but it is possible that there could be a pathway for some of this data to make it into OSM in the future.  Hope that clears it up.

**Comment by MAL315** [comment]
Hmm well maybe a year ago I had gone into the OSM irc channel and they said the best way to contribute address data (bulk) was through OA, oh well :P. Maybe some day I'll see it in there. It certainly would make sense.
