### ISSUE TITLE
us-mn-chisago 'Could not parse JSON'

### ISSUE THREAD

**Issue by mmdolbow** [openaddresses/openaddresses#1005]
Not sure why the cache is failing for Chisago County. I looked through cache.py and tried to replicate some of the scripted queries in my browser and they all went through just fine. JSON objects come back when requesting ObjectIDs, etc. Here's an example GET that works (also with POST):
https://gis.chisagocounty.us/arcgis/rest/services/GISData/MapServer/1/query?where=&text=&objectIds=%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C15%2C16%2C17%2C18%2C19%2C20%2C21%2C22%2C23%2C24%2C25%2C26%2C27%2C28%2C29%2C30%2C31%2C32%2C33%2C34%2C35&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=7&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

Let me know if there's additional research I can help with to get this one working.

**Comment by geobrando** [comment]
Hey @mmdolbow 

Took me a while but I figured it out.  Not sure what client you were using but it shouldn't have worked with POST (which is what cache.py is using to request the data).   Your source was HTTP but should have been HTTPS. The Esri server returned a 303 code and redirected to HTTPS.  When redirecting a POST, most clients are supposed to change to a GET.  So what was being returned was HTML ( a blank query form) instead of geojson.

**Comment by mmdolbow** [comment]
Sweet, thanks for the follow-up! I'm glad you figured it out.
