### ISSUE TITLE
conditional merge of csv fields

### ISSUE THREAD

**Issue by tkardi** [openaddresses/openaddresses#1077]
Is there a way to write a conditional merge of address attributes? For example the Estonian address dataset is originally structured as a hierarchy with 8 levels:

Address level | Description
------------------|---------------
A1 | 1st level admin division
A2 | 2nd level admin division
A3 | 3rd level division (city/city district name, can be blank if the name is the same as the level above)
A4 | small settlements (mostly blank)
A5 | streetnames
A6 | plot or parcel names 
A7 | house number
A8 | "part-of-house"

Addresses are not required to have all levels present so there is a multitude of possibilities for merging them:

A1 - A2 - A5 - A7
A1 - A2 - A3 - A5 - A7
A1 - A2 - A6
A1 - A2 - A3 - A4 - A6 
etcetc.

As a possibility could I use advanced merge tag to override the values for city and number tags? To code something in the line of:
        
    "advanced_merge": {
        "city": {
            "separator": ",",
            "fields": [<A2_LEVEL_NAME>, <A3_LEVEL_NAME>, <A4_LEVEL_NAME>]
        }
    }

But if a specified field value is empty how will that turn up in the end? "Tartu linn" or "Tartu linn, , "?

**Comment by NelsonMinar** [comment]
I believe it will turn up "Tartu linn, , ". Here's the Python code in question:
https://github.com/openaddresses/machine/blob/master/openaddr/conform.py#L672-L681

Is there a reason you're setting `separator` to ","? What's an example of a correct complex Estonian address?

Almost all of our sources that currently use `advanced_merge` set separator to the empty string or a space. (Japanese addresses use "-"). Depending on what we need more generally, we could modify the code so that it won't insert extra commas if some of the columns are empty. That would be an essentially invisible change for all sources but the Japanese ones, and probably not matter for Japan either.

**Comment by NelsonMinar** [comment]
(BTW, I'm thrilled that you contributed Estonian data. Aitäh!)

**Comment by tkardi** [comment]
Aga palun :) I'm just the messenger here, the adsavalik site has been up and running for some time now and I just saw there was no Estonian data up..

The official-official way as an example would be 

_Tartu maakond, Tartu linn, Riia tn 24_ which comes from merging levels A1, A2, A5 and A7 or 
_Põlva maakond, Kanepi vald, Soodoma küla, Toominga_ from levels A1, A2, A3, A6 or
_Lääne-Viru maakond, Vihula vald, Eisma küla, Kajaka väikekoht 3_ from levels A1, A2, A3, A4, A7

All address components are separated by a comma except for house number which is separated from it's parent component (whatever level it is on) by a space and "building-part" which should be separated from it's parent housenumber by a "-".

Another way around it would be if i scripted some preprocessing on the raw data and match the appropriate address-levels into the region/district/city/street/housenumber scheme. The three address from before would become then

region | district | city | street | housenumber | comment
---------|----------|------|--------|-------------------|-------------
Tartu maakond |  | Tartu linn | Riia tn | 24 | this is a simple case
Põlva maakond | Kanepi vald | Soodoma küla |  | Toominga | a non-number as housenumber is that ok?
Lääne-Viru maakond | Vihula vald | Eisma küla, Kajaka väikekoht |  | 3 | possibly could merge the A4 "väikekoht" with housenumber aswell, but then there's quite a few addresses with all A4, A5, A7 levels filled. I think this kind of mapping would be better.

There might be a few very messed up addresses aswell, but until they are encountered, better not think about them :P

Which approach would you prefer?

**Comment by NelsonMinar** [comment]
Thanks for the detailed info! You have a very good understanding of the data.

Honestly, the OpenAddresses extractor does not deal well with this level of complexity yet. Our code works pretty well when we have data from a single city and is focussed on street name and number. We have not yet done a good job on country-wide datafiles like Estonia, Denmark, or the Netherlands. We only recently even started including the city name in the output!

Depending on how much work you want to do, I see three options for how to proceed with the Estonian source file.

Option 1 (quick). Update the conform source spec to do as well as you can with our current code and transformation language. What I suggest here is you map A1 to `region`, A2 to `district`, A3 and A4 to `city`, A5 to `street`, and A6, A7, and A8 to `number`. (I may be a little wrong about which A# goes where.) No matter what you do the mapping won't be perfect and that's OK for our purposes right now. Try to minimize the separator duplication problem or if you can't, just don't worry about it.

Option 2 (more work). Get involved in our code! I've opened [an issue](https://github.com/openaddresses/machine/issues/165) on our coding project for enhancements to allow OpenAddresses to process this data and publish a better result. This ties in to some larger questions we have about the project and we would welcome outside help and input.

Option 3 (not recommended). Pre-process the data to a format better suited for OpenAddresses, as you suggest in your ticket above. I don't like that option; our vision is that we have one codebase that takes original government source data and transforms it. I'd rather not be dependent on special-purpose code someone did outside the project. That being said, there is some precedent for doing this with other sources.

**Comment by tkardi** [comment]
I'd be happy to help. I agree that option 3 is not the best of choices. And I'll see about the field mappings, though not sure if i can make it before the end of July (mostly offline and on vacation).

**Comment by NelsonMinar** [comment]
Great! Thanks again for your thoughtful comments. I'm glad to see the Estonian source is checked in; even if we don't do as good a job cleaning the source as we could, it's still a big improvement to have at all. We successfully converted 2.5M rows of data and a bunch of it looks useful, so that's progress.

If you'd like to get involved on working on the ETL code, we'd love the help. I'd particularly like to motivate these suggested improvements with an idea of who is using our data, what the data consumers' needs are. After your vacation feel free to take up the conversation in our code project! I've opened new issues for these questions there:

https://github.com/openaddresses/machine/issues/165
https://github.com/openaddresses/machine/issues/168

Thanks again for your contribution of the Estonian data and thoughts on how to process it better!
