### ISSUE TITLE
Slovenia

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses#1107]
Contradictory signals. Spatial ministry says the data is free, but the link 404s: http://www.gu.gov.si/en/services/free_access_database/territory_of_cadastral_areas/

However, e-prostor.gov.si seems more up to date and has a price list putting cadastral data at ~10,000 EUR. 

Also of interest: this presentation that includes some slides of the data: http://proceedings.esri.com/library/userconf/proc99/proceed/papers/pap499/p499.htm

I've written to addresses listed on gu.gov.si. and e-prostor.gov.si to ask for help/clarification.

**Comment by sbma44** [comment]
They've fixed the link, but it's to cadastral areas. Looks like the point database that's for sale might be the only thing available. I've asked for clarification.

**Comment by mtkc** [comment]
Hello from Slovenia with some explanations and updates!

##### Explanations

The data that you found is a database of [cadastral municipalities](https://en.wikipedia.org/wiki/Cadastral_community) (sl. *katastrske občine*), which are administrative subdivisions of cadastre database, each subdivision being approx. 7 km^2 in size. This data is not useful for OpenAddresses project, since it does not contain any addresses.

(Also, in Slovenia, parcel and building numbering used inside cadastre in different and separate from house numbering used in postal addresses. Cadastre is of no use in creating an address database.)

Official geospatial data of Slovenia is maintained by the Surveying and mapping authority of the Republic of Slovenia (sl. *Geodetska uprava Republike Slovenije - GURS*) an agency under the Ministry of the environment and spatial planning (sl. *Ministrstvo za okolje in prostor*). Generally speaking this data is not openly available.

English website: http://www.gu.gov.si/en/
Data portal (only available in Slovene): http://www.e-prostor.gov.si/

English website is pretty sparse, but it lists various vector & raster datasets that are available, terms of use, pricelists, sample data and ordering forms. Data is available to the following users:

* state and local government bodies for performing their official duties (free)
* state-registered surveyors for pefroming their work (free)
* land and building owners (free for their own properties)
* private, noncommercial, research use (free)
* commercial use (paid)

All listed users must follow a strict set of rules, one of them being that they must not make raw data available to others. GURS must be attributed as the source of data with text, hyperlink and date of the version of data.

Some datasets are available for free even for commercial use. Database of cadastral municipalities referenced above is one such example. Country and municipal borders are two other free datasets; they were used in OpenStreetMap and Wikipedia maps. Other free datasets are of little use for open mapping projects.

House numbers (addresses) are available as a SHP vector point layer inside a dataset named 'register of spatial units' (sl. *register prostorskih enot - RPE*). Besides house numbers this dataset also contains other layers: country and municipal borders, populated places, streets, school districts, post areas, statistical units and some other administrative units. House numbers layer is of high quality; points are positioned on rooftops. Currently it contains 550,643 points and costs 9,196 EUR.

##### Updates

All of the restrictions described above will shortly become irrelevant, because official Slovenian geospatial data is being opened! It was recently confirmed to me (in private communication with GURS) that the address database should become open (including commercial use) in summer 2016.

A new law that opens the data (sl. *Zakon o spremembah in dopolnitvah zakona o dostopu do informacij javnega značaja - ZDIJZ-E*) was approved by the parliament 2015-12-15, signed by the president 2015-12-23, published in the [Official Gazette of the Republic of Slovenia 102/2015](https://www.uradni-list.si/1/index?edition=2015102) 2015-12-24, came into effect 2016-01-08 and will be in use four months after that.

The new law is not easy to read as it contains very heavy legal gibberish; is actually changes the previous law on the access to public information. There are options that some datasets that are costly to produce will remain closed for another two years (this will probably be applied to aerial orthophotos).

I will post again when the address points database becomes available.

**Comment by sbma44** [comment]
Wow! What wonderful news. This would be an incredibly valuable update even if it didn't include the revelation that this data is going open. Thanks very much for posting about it here.

**Comment by sbma44** [comment]
this landed in #2926 !
