### ISSUE TITLE
Address data of India?

### ISSUE THREAD

**Issue by kishore-narendran** [openaddresses/openaddresses#1121]
This could include the state, district, and pincode information of places in India?

**Comment by sbma44** [comment]
@kishore-narendran we've looked into this quite a bit. I'd love any leads you might have, but this is a difficult problem for a few reasons:

- Survey of India has a legal monopoly on mapping data
- practical navigation is often landmark based -- e.g. it refers to a nearby shop, park, school or bus stop -- rather than based on numeric addressing

There are doubtless exceptions to both of these issues. At the moment, MapMyIndia seems to be doing the best work on the problem. But I'm not aware of any open data sources. Closing for now -- if you know otherwise **please** reopen.
