### ISSUE TITLE
Czech addresses

### ISSUE THREAD

**Issue by lxbarth** [openaddresses/openaddresses#12]
If osmlab/addresses is to expand beyond CA and US, here're Czech addresses:

http://wiki.openstreetmap.org/wiki/Import_adres_z_RUIAN

**Comment by mormegil-cz** [comment]
Not sure why the “Source Down” label, RÚIAN is one of official “primary registers” of the Czech Republic, and is the official primary source for such data. The source is definitely not down, only the specific example link used on the above-mentioned page is outdated (it referred to a year-old dump).

For an up-to-date data, see e.g. http://vdp.cuzk.cz/vdp/ruian/vymennyformat/vyhledej?vf.pu=S&_vf.pu=on&_vf.pu=on&vf.cr=U&vf.up=OB&vf.ds=Z&vf.vu=Z&_vf.vu=on&_vf.vu=on&_vf.vu=on&_vf.vu=on&vf.uo=O&ob.kod=539317&search=Vyhledat with links to data of a small town (the small floppy-disk icons in the list). In the gzipped XML, see `/vf:VymennyFormat/vf:Data/vf:AdresniMista/vf:AdresniMisto` for every address point. However, I don’t know whether Conform would be able to use the file without preprocessing, as this is not just GML but a specific XML file with a few quirks added. For instance, the position is in EPSG:5514 instead of WGS84. Also, street names are not included in every address point, but are separately in `/vf:VymennyFormat/vf:Data/vf:Ulice/vf:Ulice` and are referred to using an ID. Etc.

**Comment by sbma44** [comment]
This is great, @mormegil-cz! Custom GML variants are sadly [nothing new](https://github.com/openaddresses/openaddresses/tree/master/scripts/es) around here, so I imagine we could handle this. I'm afraid that I don't have an ETA for being able to tackle this, though.

**Comment by sbma44** [comment]
@mormegil-cz I'm digging into this now -- can you tell me which field from the layers in the GML file is the house number? I have clicked around a bit in AdresniMista but it's not completely clear to me.

**Comment by mormegil-cz** [comment]
I’ll try a short summary. (The official specification of the RÚIAN format should be at [ČÚZK](http://www.cuzk.cz/Uvod/Produkty-a-sluzby/RUIAN/2-Poskytovani-udaju-RUIAN-ISUI-VDP/Vymenny-format-RUIAN/Vymenny-format-RUIAN-%28VFR%29/Struktura-a-popis-VFR-1_3_0-%281%29.aspx), it is Czech-only, however. I don’t know of any official English specification.)

You are interested in `/vf:VymennyFormat/vf:Data/vf:AdresniMista/vf:AdresniMisto` where each record corresponds to a single address point. In this, the interesting pieces are:
* `ami:Geometrie/ami:DefinicniBod/ami:AdresniBod/gml:Point` – geographic location of the address point (in [S-JTSK](https://cs.wikipedia.org/wiki/S-JTSK))
* `ami:Psc` – ZIP code
* `ami:Ulice` – street; this contains an identifier which refers to `/vf:VymennyFormat/vf:Data/vf:Ulice/vf:Ulice`, containing the street name in `uli:Nazev`.
* `ami:CisloDomovni`, `ami:CisloOrientacni`, `ami:CisloOrientacniPismeno` all refer to various pieces of the house number, as our house numbering system is a bit complicated. ;-)

Czech addresses generally contain _two_ house numbers: One (“číslo popisné”, “conscription number”, see [addr:conscriptionnumber](http://wiki.openstreetmap.org/wiki/Key:addr:conscriptionnumber)) is a unique identifier within the whole village/town (or a town district), the other (“číslo orientační”, “street number”, see [addr:streetnumber](http://wiki.openstreetmap.org/wiki/Key:addr:streetnumber)) is a sequential number within a street. Every address point have the conscription number (in fact, some houses have “provisional number” instead of conscription numbers, but I think you might ignore that distinction), not all addresses have the street number – not all villages/towns have streets, and not all of those who have use street numbers. So, an address might generally look like this:
* _Street 853_ – conscription number only (`ami:CisloDomovni`)
* _Street 853/15_ – conscription number / street number (`ami:CisloDomovni` / `ami:CisloOrientacni`)
* _Street 853/15b_ – sometimes, street numbers must be extended with a letter; in that case, `ami:CisloOrientacniPismeno` is used to store the additional letter (`ami:CisloDomovni` / `ami:CisloOrientacni` + `ami:CisloOrientacniPismeno`)

Example data for those two variants:
* [539317](http://vdp.cuzk.cz/vdp/ruian/vymennyformat/vyhledej?vf.pu=S&_vf.pu=on&_vf.pu=on&vf.cr=U&vf.up=OB&vf.ds=Z&vf.vu=Z&_vf.vu=on&_vf.vu=on&_vf.vu=on&_vf.vu=on&vf.uo=O&ob.kod=539317&search=Vyhledat) is a town with streets but without street numbers.
* [531723](http://vdp.cuzk.cz/vdp/ruian/vymennyformat/vyhledej?vf.pu=S&_vf.pu=on&_vf.pu=on&vf.cr=U&vf.up=OB&vf.ds=Z&vf.vu=Z&_vf.vu=on&_vf.vu=on&_vf.vu=on&_vf.vu=on&vf.uo=O&ob.kod=531723&search=Vyhledat) is a town with streets and street numbers.

**Comment by sbma44** [comment]
@mormegil-cz tremendously helpful. I had a script collect the GML files yesterday, and hope to look into processing them this week. Your explanation gives me just what I need.

**Comment by sbma44** [comment]
Download script is here, btw:

https://github.com/openaddresses/openaddresses/tree/cz/scripts/cz

 Full download appears to be ~18GB. Still looking for time to dig in deeper.

**Comment by sbma44** [comment]
@mormegil-cz I am finally working to get this data imported today, and having considerable success thanks to your excellent notes. I am focusing on collecting the `ami:CisloDomovni` records, since it sounds like they have better coverage and would be closer to the official number. Is that correct, or would you not use the conscription number when writing an address (for sending a letter, for instance, or using a web form)?

I'm seeing a lot of files that lack `Ulice` records, and right now my scripts don't collect any addresses from them. My best guess is that these are small towns that have `ami:CisloDomovni` but no street names. Is there a record in the XML that contains the town name? I have looked at the file you pointed to for `Základní` but that string is only present in an XML comment, as far as I can tell.

**Comment by sbma44** [comment]
OK! I found the place name after all. But my other question stands: should I use `ami:CisloOrientacni` when it is available? What would you expect a geocoder to handle?

**Comment by mormegil-cz** [comment]
You should definitely handle both numbers, if possible. For towns which do use `ami:CisloOrientacni`, it is often the most used number in common communication. You are right that the conscription number is the more official number; when writing a letter, you might use it quite often, but when explaining travel instructions, you would most definitely use street number, as conscription numbers are unusable for that (by their generally random distribution in the street).

So, when someone states he wants to know the location of an address, e.g. “Jungmannova 22, Prague”, he _probably_ wants to know the location of [Jungmannova 742/22](http://www.openstreetmap.org/node/296481429) (i.e. he means the street number), even though he _might_ have meant [Jungmannova 22/9](http://www.openstreetmap.org/node/296481429) (i.e. the conscription number). This is the obvious problem of the numbers being ambiguous.

If you cannot handle _both_, I’d recommend using the street numbers (`ami:CisloOrientacni`) where present; in towns without them, use conscription numbers. In towns without both street numbers and street names, conscription numbers are used directly after the town/village name, e.g. “Vojkovice 153” in [535290](http://vdp.cuzk.cz/vdp/ruian/vymennyformat/vyhledej?vf.pu=S&_vf.pu=on&_vf.pu=on&vf.cr=U&vf.up=OB&vf.ds=Z&vf.vu=Z&_vf.vu=on&_vf.vu=on&_vf.vu=on&_vf.vu=on&vf.uo=O&ob.kod=535290&search=Vyhledat).

**Comment by sbma44** [comment]
Okay! I think I've got it and can handle both. Thanks again for the insight -- I'll update this thread once the data has finished processing (there's quite a lot of it) and I've submitted a pull request.

**Comment by sbma44** [comment]
merged! https://github.com/openaddresses/openaddresses/issues/1100
