### ISSUE TITLE
Russian Sources

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#127]
Another source that we will need to figure out licensing with.

http://maps.rosreestr.ru/arcgis/rest/services

**Comment by blacktopol** [comment]
New link to ArcGIS service.
http://pkk5.rosreestr.ru/arcgis/rest/services

Russia has created FIAS (Federal Information Address System). 
FIAS database can be downloaded here https://fias.nalog.ru/Updates.aspx
But this addresses doesn't have coordinates.

Here is the public cadastre map of Russia
http://pkk5.rosreestr.ru
License information available from left menu ("?" button)
It has a geocoding services
http://pkk5.rosreestr.ru/arcgis/rest/services/Address

**Comment by sergiyprotsiv** [comment]
This would be a fantastic source, but I do not see the way to get the data (since the rest server does not expose querying). If it is possible to nicely scrap the ESRI Geocoder (http://pkk5.rosreestr.ru/arcgis/rest/services/Address/gkn/GeocodeServer), would be wonderful.
The license seems quite permissive (http://data.gov.ru/information-usage), but I am not 100% sure that that is the actual license for the data or the license to the metadata about the cadastral data (sigh..)

**Comment by justinelliotmeyers** [comment]
@sergiyprotsiv any ideas or new leads on Russian data? The sources listed above aren't usable.  Thanks!!

**Comment by sergiyprotsiv** [comment]
No, not that I know of. The FIAS database seems to be pretty good for the list of addresses, but it has no coordinates. And the "rosreestr" data was apparently only publicly available for a short period after launch a few years back (judging from the Russian geodata forums), and then they shut down the mapserver APIs.
