### ISSUE TITLE
Portugal

### ISSUE THREAD

**Issue by ingalls** [openaddresses/openaddresses#170]
http://www.portugal.gov.pt/en.aspx
gabinete.seaot@mamaot.gov.pt

**Comment by ingalls** [comment]
Stale - no response. Someone else is welcome to take this on.

**Comment by sbma44** [comment]
I corresponded with Felipe Cruz back in January. He's blogged about open data efforts in Portugal, and pointed me toward their open data portal:

![image](https://cloud.githubusercontent.com/assets/31717/9228457/9971993e-40e6-11e5-8ff1-9d9b5529d763.png)

Portugal [is building a cadaster](http://www.dgterritorio.pt/static/repository/2014-04/2014-04-03105202_b511271f-54fe-4d21-9657-24580e9b7023$$5D83BE99-238C-4727-83D4-712E7C3188A0$$7140EDFA-BFEA-4E41-81B8-F7A924284B33$$file$$pt$$1.pdf). But they historically have not had one (lost the link, apologies).

Probably worth checking in with the INSPIRE process to see if they've made progress otherwise.

**Comment by joao** [comment]
@ingalls @sbma44 

Saw this ticket in 2014, did some research back then and no resource was available. I thought I had commented but noticed today I didn't, sorry.
Going to share the research I did, as there was no progress made in the meantime in Portugal and this might serve as future reference for anyone looking on how to get the data.

The only public dataset that comes even closer to what is necessary to add Portugal to OpenAddresses, is one of made available by the National Post office, which has all the streets in Portugal, with their postal-codes and house numbers.
It is provided by the national post office, but it is lacking geographic coordinates.
You can see it here in a repository:
https://github.com/centraldedados/codigos_postais/tree/master/data

Also on this page you can see more details on that dataset (better Google Translate it):
http://centraldedados.pt/codigos_postais/


The open data portal of the Government, built in 2011 and still in 'beta', is a ghost town:
http://www.dados.gov.pt/
It has always been more focused in publishing spreadsheets with aggregated conclusions without raw data (ex: percentage of unemployment in each district).
Unfortunately all of these 'open data portals' in the country are outsourced projects to big consulting companies, that work on them for a couple of months, with no improvement or upgrade plan afterwards. Then the projects are just kept in maintenance mode, as it has happened with one referenced above, IGEO (http://www.igeo.pt)

I will try in the coming months to get hold of a contact inside one of these government departments to see if it possible to make anything they have publicly available.

**Comment by sbma44** [comment]
This is a shame, but I really appreciate the info, @joao -- it's really useful to have and will probably be helpful in the future.

**Comment by astoff** [comment]
For what it's worth, [the OSM wiki](https://wiki.openstreetmap.org/wiki/WikiProject_Portugal/Lista_de_Fontes#Sistemas_de_informa.C3.A7.C3.A3o_geogr.C3.A1fica) lists GIS departments of several municipalities.

**Comment by joao** [comment]
Portugal now has all residencial buildings addresses available with a proper license:
http://inspire.ine.pt/AD/atom/downloadservice.html

XML: http://inspire.ine.pt/AD/atom/downloadservice.xml

Have confirmed with the person responsible for the dataset (who was in the conversation at [issue #3025](https://github.com/openaddresses/openaddresses/issues/3025)) that there aren't any licensing issues.
It is even stated on the URLs I pasted above 'sem restrições', which translates to 'no restrictions'.

Don't have the skills to make a pull request with the data in a proper format, but can aid with any translations, downloads or support tasks anyone might need to import the data.
The data is in GML files, with several projections to choose from.

CCing @iandees and @migurski as they also had to work to remove the previous Portugal data and will surely welcome these news.

**Comment by migurski** [comment]
Thank you @joao, I’m excited to get this data included! I’ve not been able to successfully read the URLs above; they seem to be Atom XML feeds without descriptive information. Could you confirm the first one?

**Comment by sergiyprotsiv** [comment]
Thanks a lot, @joao!  This is very welcome news! I will take a close look at this soon and will try to do the import. 

The Atom feeds can be opened in Chrome. The original feed consists of pointers to several pages per NUTS 2 regions of Portugal, like this: http://inspire.ine.pt/AD/atom/CDG_AD_BNM_pc_Centro_Atom_en.xml

Each of those in turn contains a list of links to GML files of addresses per municipality, for example http://inspire.ine.pt/AD/atom/gml/Addresses_0108_EPSG4258.zip.

These GML files have some pretty complex schema. I am pretty sure it is an official INSPIRE schema, but I will only be able to dig into this in the coming days. 

If anyone has experience with automatic conversions of INSPIRE GMLs into a format useful for OA, let me know. In any case, it seems like this would have to be a "scripted" import, since we do not want a source per municipality and each of the links is a special INSPIRE GML. Maybe if we can eventually have an "INSPIRE" type in the conform object, this could be done automatically.

**Comment by sbma44** [comment]
I haven't dug into the Portuguese feeds, but will note that when I processed our first source for Spain (since replaced, iirc) it consisted of Atom feeds pointing to GML docs. The code I used to process this source can be found here: https://github.com/openaddresses/openaddresses/tree/master/scripts/es

Most of the GML processing can be found in https://github.com/openaddresses/openaddresses/blob/master/scripts/es/gml_to_csv.py

The README and the Makefile provide the best overview of how the pieces fit together (I confess I've forgotten pretty much all of the details) https://github.com/openaddresses/openaddresses/blob/master/scripts/es/Makefile
