### ISSUE TITLE
Statewide NJ data has street names in housenumber fields

### ISSUE THREAD

**Issue by dianashk** [openaddresses/openaddresses#1841]
Seeing a lot of invalid house numbers in this file. Most, if not all, of them have the street name duplicated instead.

https://github.com/openaddresses/openaddresses/blob/d1efb0a64df583fb8f2a40270fb878593722aeec/sources/us/nj/statewide.json

<img width="578" alt="screen shot 2016-07-18 at 8 28 32 pm" src="https://cloud.githubusercontent.com/assets/5446511/16934657/6ca037c4-4d26-11e6-9143-48ed2047caf6.png">

**Comment by trescube** [comment]
There's some history [here](https://github.com/openaddresses/openaddresses/pull/1722), but I think it's the same regex issues that Tennessee statewide [was having](https://github.com/openaddresses/openaddresses/pull/1839).

**Comment by erictheise** [comment]
It's been months since I've worked directly with the output files but at that time I found files like this and also–I don't remember the specifics–with lines I thought incomplete and had to reject for my use.

At the time I thought that there should be more black box QA in the processing cycle, checking that rows had some minimum amount of data (these duplicate street names would generate an exception) and also to do some level of `ST_WITHIN` work to gather and report stats about potential outliers.

I haven't looked to see if any of that work is currently in the project but I'd be interested in contributing something like that.

**Comment by trescube** [comment]
I don't recall seeing it before, but there appears to be an points layer now:

http://geodata.state.nj.us/arcgis/rest/services/Features/Addresses_and_Names/MapServer/0

The fields are much cleaner.

**Comment by trescube** [comment]
Ah, I see that's already been pointed out on the other issue.  I'm going to cache the points.

**Comment by nvkelso** [comment]
I see what you did there, with the points ;)

**Comment by trescube** [comment]
Scratch all that, @migurski switched to use points from a GDB file in [early January](https://github.com/openaddresses/openaddresses/blob/master/sources/us/nj/statewide.json).

I'm closing this.
