### ISSUE TITLE
Strange Italy data

### ISSUE THREAD

**Issue by migurski** [openaddresses/openaddresses#1902]
I am seeing some funky projection offset business in Italy. Here is a screenshot in Rimini:

<img width="937" alt="rimini" src="https://cloud.githubusercontent.com/assets/58730/17571155/e171bed0-5f03-11e6-8467-c05800ce5558.png">

**Comment by sergiyprotsiv** [comment]
The points looks good when I load them in QGIS offline. I think this is the special projection Italian sources use (EPCG 25832), which is based on the ESTR89 datum instead of the usual WGS84. However this should only have an effect of a few meters.

In case of Rimini there is also an older source "it/er/rimini", which could result in some duplication. I am not sure which one is the "offending" source in your map - offline they look almost identical, though with a few-meter shift indicating the datum issue.

<img width="943" alt="rimini" src="https://cloud.githubusercontent.com/assets/1951020/17571935/2c1f1100-5f07-11e6-8dab-47a671a347b0.png">

**Comment by migurski** [comment]
I checked both, and the older one is wrong. Thanks for investigating, I have removed it so this newer, better source can stay!
