### ISSUE TITLE
Add addresses in Newport, OR

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1954]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
will have to call:
Lincoln County Assessor

225 West Olive Street, Room 207
Newport, Oregon 97365

tel: (541) 265-4102
fax: (541) 265-4148

**Comment by nvkelso** [comment]
Will likely made redundant with https://github.com/openaddresses/openaddresses/issues/2148.

**Comment by nvkelso** [comment]
Oregon statewide data in #2148 doesn't include Lincoln county :(

**Comment by justinelliotmeyers** [comment]
Spoke to assessor, no data... Called e911 dispatch.  5037633328 Robbie hurry.  Left a voicemail.

**Comment by justinelliotmeyers** [comment]
Robbie called back.  Spoke for 15 minutes,. Need to formally request data.  Person in charge of Salem and three counties data requests will return Wednesday.  Will follow up first thing Wednesday morning.

**Comment by justinelliotmeyers** [comment]
called last wednesday (12/21/2016) - left a voicemail.  Called 12/27/2016 and left another voicemail.

**Comment by justinelliotmeyers** [comment]
called Salem IT GIS dept 503-588-6351 and left a voicemail

**Comment by justinelliotmeyers** [comment]
Okay, we are good to go. Need to sign a license agreement, terms are outdated (by ten years), but she still needs it signed, and we just need to explain our use of the data. Since we are incorporating in a derivative, there is no problem with us using the data in OA. We just need to explain that the data will be incorporated into OA, and what OA is. I know it says we can't, and I explained that to her, but she said we can. So I'm not sure what our play is here? They are working on a open data site, and she is working with their legal department to get the terms updated, but no idea when that will be.

**Comment by justinelliotmeyers** [comment]
@nvkelso let me know how you would like me to handle this.  Thanks!

**Comment by iandees** [comment]
The license in question is [GIS_PLA20161228.docx](https://github.com/openaddresses/openaddresses/files/727947/GIS_PLA20161228.docx). Unless we get it in writing that it's OK to ignore the no-redistribution and no-commercial-use sections of this license we can't use their data.

**Comment by justinelliotmeyers** [comment]
sent an e-mail asking if the terms can be changed; they have an open site coming soon with the data. Worst case, we have to wait...

**Comment by justinelliotmeyers** [comment]
Hi Justin,
 
No, I have no way of expediting Legal, and having them prepare a single license just for your use.  No, I cannot commit to a time when open data will be final for us.
 
What you can do is send me a narrative on how you intend to use the data.  And, if there is specific language in the PLA that you want to strike or re-write, then identify it… and I will take it from there.
 
Thanks,
Sue

**Comment by justinelliotmeyers** [comment]
@nvkelso can we fill out form - cross off what we don't want and submit? Worse case scenario is they say no. They are in process of creating open data portal - no idea when it will be finished. The terms she sent are outdated, but they have to send them.

**Comment by nvkelso** [comment]
@iandees Is the form striking and offering back to this source something you'd need to do as an OA legal officer?

**Comment by iandees** [comment]
I crossed out the Permitted Use and Restrictions on Use sections of the license and posted it here: [GIS_PLA20161228.docx](https://github.com/openaddresses/openaddresses/files/1181281/GIS_PLA20161228.docx)

Alternatively, we could write something about how we want to use the data and try to make it fit in with 2.2's "authorized in advance in writing by the City of Salem".

It would probably be better/simpler/less confusing to ask them to release their data under something like CC-BY rather than whatever this document is.

**Comment by justinelliotmeyers** [comment]
http://opensalem-salem.opendata.arcgis.com/datasets/d686030c3b1a474bbe019320b77ce7e6_0

**Comment by justinelliotmeyers** [comment]
they are reviewing so we can get data for the three counties instead of just city. fingers Crossed!

**Comment by justinelliotmeyers** [comment]
here is my POC: Blohm Susan GIS Lead Analyst City of Salem sblohm@cityofsalem.net (503) 763-3429

**Comment by justinelliotmeyers** [comment]
just followed up with a call. She never gave it to their legal team to look at..... So now she is ;)  Stay tuned

**Comment by justinelliotmeyers** [comment]
sent another follow-up email...

**Comment by arch0345** [comment]
#6170 adds addresses for Newport

Are there any updates for obtaining addresses from Lincoln County?

**Comment by justinelliotmeyers** [comment]
@arch0345 I'll check tomorrow

**Comment by arch0345** [comment]
I've joined the shapefile with the other dbf here: [taxlotaddress.zip](https://drive.proton.me/urls/JS73QSP7WM#09VRmGy0c3AL)

@iandees would you be able to upload this to data.openaddresses.io?

**Comment by iandees** [comment]
Uploaded to https://data.openaddresses.io/cache/uploads/iandees/f75ee2/taxlotaddress.zip
