### ISSUE TITLE
Add addresses in Winslow, AZ

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1957]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
no e-mail for any department listed: http://www.winslowaz.gov/

will have to call later today.

**Comment by justinelliotmeyers** [comment]
called planning zoning and left a voicemail
928-289-2422

**Comment by justinelliotmeyers** [comment]
called again and left second voicemail :|

**Comment by justinelliotmeyers** [comment]
Navajo County has map: http://www.navajocountyaz.gov/Departments/Treasurer/Property-Taxes/Property-Tax-Map-Search

emailed their treasurer asking about data.

**Comment by justinelliotmeyers** [comment]
Greetings Justin,
 
We have not typically given out our e911 information outside of state and emergency service providers. We have parcels with APN’s from the Assessor that we give out for free. The more detailed information from the assessor comes with a fee unless the Assessor waves the fee as in the case of the state, federal, other government or schools request. The site address from the assessor is not accurate though, they focus more on mailing address than physical since the APN is all that is needed for their locating. They have been improving though. If interested, I would have to check with the Assessor again, but I believe the fee for their data is $1,000. Attached is the form we require anyone obtaining data from us to fill out. And if you’re still interested, I will confirm the fee and put together an invoice.
 
Regards,
 
Bryan Cook | Senior Engineering Project Manager II
100 West Public Works Drive
PO Box 668 | Holbrook AZ 86025
Phone (928) 524-4047 | Fax (928) 524-4122
NavajoCountyAZ.gov | Facebook/NavajoCounty
Teamwork | Accountability | Integrity | Excellence | Innovation

**Comment by justinelliotmeyers** [comment]
just called him, left a voicemail

**Comment by nvkelso** [comment]
Only 10k people in the town, but 107,449 in the entire county. I'm a little skeptical of semi-expensive parcel data that other GIS professionals consider inaccurate :\

**Comment by justinelliotmeyers** [comment]
After a phone call, they will not share with the public freely. They are in the process of creating an address point dataset (based off of parcel centroids). But haven't started. Plan on completing by end of summer, but no deadline. Can share empty parcel data freely, but no attributes.

**Comment by nvkelso** [comment]
Unattributed polygons, yum.

**Comment by justinelliotmeyers** [comment]
Yeah... The call took the wind out of my sail for the day.
