### ISSUE TITLE
Add addresses in Wilkes-Barre, PA

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/openaddresses#1978]
Status:
- [ ] **Research sources** and propose best source (and it's data license)
- [ ] **Review proposed source**
- [ ] **Approve source** based on review comments
- [ ] **Add** to OpenAddresses

_NOTE: Proposed source notes should include basic column mapping to OpenAddress data model._

**Comment by justinelliotmeyers** [comment]
emailed gis@luzernecounty.org the county asking for data 11/3/2016

**Comment by justinelliotmeyers** [comment]
also emailed 
Kurt Sauer
Director of OCD
570-208-4135
ksauer@wilkes-barre.pa.us

**Comment by justinelliotmeyers** [comment]
also emailed Fred J. Rosencrans
9-1-1 Executive Director
100 Young Street
Hanover Township, Pa.  18706
Phone: (570) 826-3058
Fax: (570) 826-3056
 

E-Mail: Fred.Rosencrans@luzernecounty.org

**Comment by justinelliotmeyers** [comment]
Fred replied:
Justin,

I forwarded your request to the County GIS Director Dave Skoronski

**Comment by nvkelso** [comment]
@justinelliotmeyers want to tickle these folks again, please?

**Comment by justinelliotmeyers** [comment]
e-mailed 
gis@luzernecounty.org
fred.rosencrans@luzernecounty.org

will follow-up Wednesday if I do not hear back

**Comment by justinelliotmeyers** [comment]
Called and left a voicemail with director:
5708251521
David Skoronski

**Comment by justinelliotmeyers** [comment]
Justin,
 
At this time we cannot extract those data elements from our internal proprietary emergency dispatching system for openly licensed purposes.  Additionally, the internal data we manage does not have postal codes inherent in the data.  Keep in touch for any future developments in this area.
 
We do have a policy for enhanced digital data distribution that includes Tax Parcel data (tax mailing addresses only) and other data.  Our policy does include extensive terms & conditions at this time.
 
Best,
Dave
 
David T. Skoronski, GISP
Luzerne County
Director
GIS/Mapping Department
200 North River Street
Wilkes-Barre PA 18711
Office: 570-825-1521
dskoronski@luzernecounty.org

**Comment by justinelliotmeyers** [comment]
Justin,
 
Since the Tax Assessor’s SITUS address field is so very riddled with bad data, we do not include SITUS in data deliveries (perhaps that will change in the future, but I’m not in control of their database).  I speak for the E911 folks related to data inside their CAD system and they are not doing extracts at this time.
 
Attached and below my signature is our boiler-plate information for data distribution.
 
Take care,
Dave
 
David T. Skoronski, GISP
Luzerne County
Director
GIS/Mapping Department
200 North River Street
Wilkes-Barre PA 18711
Office: 570-825-1521
dskoronski@luzernecounty.org
 
DIGITAL DATA:
 
Attached is our standard document package that should cover most of your questions (below & attached).  As for Tax Parcels, we have our “Enhanced” GIS Tax Parcels Data product that combines a number of Tax Assessment & Recorder of Deed database items to the GIS data.  Most of the critical attributes are included (Owner, Mailing Address, PIN#, Assessed Values, Deed Book & Page, Lot size, etc.).  We also have reciprocal agreement flexibility in order to exchange data to reduce your cost.  For other layers such as Addressed Structures, Streets or Aerials, etc. please refer to the attached Fee Schedule.
 
We can also Email you a PDF map (or maps) of your AOI at our standard rate of $5/map.  We can also mail hardcopy products as well.  If this is the route you wish to take, please speak to a analyst in our Mapping office at 570-825-1550.
 
Basically, our “Enhanced Tax Parcels” are priced at three tiers:
1.      By the Parcel $0.05/parcel + $25 min processing fee (corridor analysis, city block analysis… delineated by customer)
2.      By the Municipality (76 municipalities available): $75 ea
3.      Entire County (approx. 170,000 Parcels): $4000
 
Please look over our documents and ask me any questions you might have. 
 
The typical procedure when people know what items they need goes as follows: 
1)      Fill our Request form, sign & mail (or Email if digitally signed)
2)      If a reciprocal agreement is approved, define the agreement on the request form.
3)      If applicable, include a check for the total Fees payable to “County of Luzerne” and send to:
 
ATTN: Mapping/GIS Data Project
200 North River Street
Wilkes-Barre  PA 18711
 
Other important information:
 
Recently an ordinance was adopted which allowed us to create policies for enhanced digital GIS data distribution.  As a part of our policy, we require all entities requesting data to complete a “GIS Data Request Form” which also acts as a license agreement (attached).  Also, please review all terms & conditions stated in the “GIS Terms and Conditions” and “Digital Data Copyright Disclaimer” documents (attached).  Finally, review the “GIS Fee Schedule” file to calculate the total fees required (not applicable if a reciprocal agreement is in place).
 
If your entity is outsourcing any of this data to any third party, they must also (additionally) follow this request policy (as stated in the Terms & Conditions document).
 
All enhanced GIS data has a current Copyright and these materials are protected by federal and international law including Title 17 of the United States Code.  You are prohibited from making any unauthorized reproduction, adaptation, performance, display or distribution of these materials.  Violators are subject criminal and civil liabilities including imprisonment and damages up to $150,000 per work.

**Comment by nvkelso** [comment]
So no effectively no redistribution even if we paid for access :\

**Comment by justinelliotmeyers** [comment]
@nvkelso found:http://www.nepa-alliance.org/

which leads you to  http://services.arcgis.com/zIzHhk5p87uNK9TM/ArcGIS/rest/services/ASTA_070820106/FeatureServer/0 which has parcels for Wilkes-Barre. May fill in https://github.com/openaddresses/openaddresses/issues/2409 as well if I find their county/ city

**Comment by nvkelso** [comment]
Checked and doesn't fill in #2409, but does work for this issue :)

**Comment by justinelliotmeyers** [comment]
no data
