### ISSUE TITLE
au/countrywide using wrong postcode field

### ISSUE THREAD

**Issue by andrewharvey** [openaddresses/openaddresses#2164]
au/countrywide is using the gnaf-loader `locality_postcode` field as the address postcode: https://github.com/openaddresses/openaddresses/blob/master/scripts/au/gnaf.sh#L63

`locality_postcode` is the postcode of the locality for this address, not the postcode for this address point. https://github.com/minus34/gnaf-loader/blob/dfc2a2e22420e70ebd2e52c8a9aa112b11bd9f32/postgres-scripts/03-12-reference-populate-addresses-2.sql#L41

I think OA should be using the 'postcode' field.

/cc @minus34 in case you have any guidance here?

**Comment by minus34** [comment]
Due to the unofficial method used by the PSMA, the address level postcodes are usually worse than the locality_postcode values. The aggregation method used to generate locality_postcode values knocks out a good number of the postcode outliers.

FYI - the PSMA aren't actually allowed to use the postcodes in the Postal Address File in GNAF even though its a key GNAF data source; due to Australia Post licensing limitations.  This may change in the future as there are ongoing (multi-year) discussions.

**Comment by andrewharvey** [comment]
@minus34 Thanks for the explanation.
