### ISSUE TITLE
Vitebsk Address Data!!!!!!!!!!!!!!!!!!!! (Belarus)

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2353]
http://vitebsk.gismap.by/ArcGIS/rest/services/Vblotsset/MapServer/0

not sure about the coverage, but looked at a handful, and they look good.

**Comment by trescube** [comment]
This probably isn't countrywide since there are only 19,773 records.  The `ADDRESS` field I think contains the entire address but it's very muddled and I don't speak Russian so I have to investigate further.

**Comment by trescube** [comment]
It appears to be https://en.wikipedia.org/wiki/Vitebsk_Region

**Comment by sergiyprotsiv** [comment]
Hi, this is indeed just Vitebsk and the coverage is good but not complete. There have been quite a few efforts there (in Belarus, Ukraine, Russia, Kazakhstan, etc.) to put up addresses online both from private individuals (lots of effort to get the data for their car GPS systems) and the governments (most countries have an openly accessible cadastral map). The problem with cadastral maps is that it is not usually possible to access the underlying data directly, but some regions published their data separately.

I am a Ukrainian and a Russian native speaker, so will try to get good coverage of the region. So far spent some time to get the best source for Moscow (will publish once I finish the processing script, it's quite messy), a few other Russian regions, as well as countrywide Kazakhstan.

One question I have is that these sources usually reference buildings and therefore have polygon geometry. Can I point the conform object to these layers and it will extract the centroids automatically or should there be a pre-processing step?

**Comment by trescube** [comment]
The OA machine calculates the polygon centroid for the lat/lon value.  

Since you're a Russian speaker, can you give me some guidance on parsing some addresses?  

* Докшицкий р-н, Порплищенский с/с, д. Порплище, ул. И.Курец, 17
* гп. Бешенковичи, ул. Я.Колоса, 8
* Бешенковичский район, Соржицкий с/с, д.Дашково
* г. Витебск, ул. Набережная 2-я, д. 5

I assume the values are comma-delimited and the first field is the city but I've not had much luck deciphering the rest.  From a glance can you give some indication what the other fields are?

**Comment by trescube** [comment]
By substituting in other region names, I found a few more:

* [Mogilev](http://mogilev.gismap.by/ArcGIS/rest/services/)
* [Gomel](http://gomel.gismap.by/ArcGIS/rest/services/)
* [Brest](http://brest.gismap.by/ArcGIS/rest/services/) (returns a 500, though)
* [Grodno](http://grodno.gismap.by/ArcGIS/rest/services/)

Minsk is missing, but the interactive map seems to farm those out to other region's GIS servers.

**Comment by sergiyprotsiv** [comment]
Sure, but this does not look particularly easy in this case. 

In short, most countries that have inherited the Soviet systems have districts ("raion") as the main municipal governance units (similar to US counties, but generally smaller). Usually the name of the town/village/hamlet need only be unique wishing the raion, so it is often given as part of the address.

"район" is the Russian term and "р-н" is a commonly used short version. "с/с" is the rarely used intermediate level between the raion and the village name, usually can be ignored. "д." or "с." usually names village (though if followed by a number, e.g. "д. 5" it means "house number 5"). 

"гп", "пгт", "г" and probably others are used to name town of differs sizes ("г" = город) covers proper large cities. Confusingly, largest cities have rains on their own (which can safely be ignored and if it is part of the address it will come after the name of the city).

 "ул" = "улица" is one of the possible types of streets (by far the most common) and should generally be 

So, these addresses should be parsed like this (district could likely be dropped too, since it will unlikely be universally present):
- Докшицкий р-н, Порплищенский с/с, д. Порплище, ул. И.Курец, 17    :      district: "Докшицкий район", city: "Порплище", street: "ул. И.Курец", housenumber: "17"
- гп. Бешенковичи, ул. Я.Колоса, 8     :      city : "Бешенковичи", street: "ул. Я.Колоса", housenumber: "8"
- Бешенковичский район, Соржицкий с/с, д.Дашково     :   district: "Бешенковичский район", city: "Дашково" (no street or house here)
- г. Витебск, ул. Набережная 2-я, д. 5     :    city: "Витебск", street: "ул. Набережная 2-я", housenumber: "5"

**Comment by sergiyprotsiv** [comment]
Sorry, did not finish the sentence: 
"ул" = "улица" is one of the possible types of streets (by far the most common) and should generally be kept as part of the street name as there can definitely be a "Pravda street" and "Pravda avenue" within the same city (to use an example of my grandmother's address).

**Comment by migurski** [comment]
@sergiyprotsiv, thank you so much for offering your expertise here.

**Comment by sergiyprotsiv** [comment]
The Minsk data is here: http://gismap.by/arcgis/rest/services/Public/Uchastki_Minsk_public/MapServer/0 but it does not seem to have the address field (even though it is listed as the display name). Does not open in Chrome for some reason - try another browser.

Found this by following the network requests when scrolling around this map: http://gismap.by/mobile/ Maybe eventually can dig up more.

**Comment by trescube** [comment]
Fixed in #2354, closing
