### ISSUE TITLE
Cowichan Valley Regional District, BC, Canada

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#2442]
![cvrd](https://cloud.githubusercontent.com/assets/5324316/22371111/1e3b6c64-e463-11e6-8f9a-c812b938dd92.jpg)

yellow-new (under red in drawing order *all new!)
red-existing

http://www.cvrd.bc.ca/2024/Geospatial-Data

**Comment by nvkelso** [comment]
Looks like we'd need their approval to distribute this data, per their terms:

`The End User must not alter or change, distribute, transfer, loan, lease or otherwise make the CVRD spatial data available in any form in whole or in part to any person or body without the prior written consent of the CVRD.`

**Comment by justinelliotmeyers** [comment]
e-mailed:
Rob Grant
GIS Supervisor
rgrant@cvrd.bc.ca
Phone: 250.746.2680

to see if we can use it in OA

**Comment by justinelliotmeyers** [comment]
Just got off the phone with him;
If we:
1)reassure we download the data weekly for most current version
2)supply metadata with download (source date downloaded)
3)let end users know what source of data is and where they can download it from

we are good to go. I believe he would give us written permission (**he said by doing those three things, it is in the terms that we can use the data).
