### ISSUE TITLE
Possible Flanders, Belgium data

### ISSUE THREAD

**Issue by migurski** [openaddresses/openaddresses#3002]
Report of new data via Twitter: https://twitter.com/emacgillavry/status/865086118097805312

**Comment by nvkelso** [comment]
This is now ready to download, sounds like new source for whole country including Flanders, CC-BY:

- https://opendata.bosa.be/index.nl.html
    - `All XML files in 1 ZIP (+/- 250 MB, weekly updates)`
- https://twitter.com/Toon/status/1138432841900052480
- https://dt.bosa.be/fr/a_propos_de_bosa/actualite/belgian_streets_and_addresses_best_disponible_sous_forme_de_donnees

For posterity, here's the before image:

![image](https://user-images.githubusercontent.com/853051/59393153-401afa80-8d2f-11e9-9d7e-2c46ab8a24ab.png)

**Comment by nvkelso** [comment]
@trescube want to have a crack at this one?

**Comment by barthanssens** [comment]
Hi, I'm the maintainer of the opendata.bosa.be website and the data.gov.be open data portal in Belgium.

I'm actually coaching a few students on the "Open Summer Of Code 2019" to convert the custom XML files to csv and other formats, so we could do the work for you (creating separate files per region and hosting them somewhere) and create a few pull requests

The data fully covers the three regions of Belgium, by the way, but unfortunately each of them has a slightly different license, and comes directly from the authoritave sources of these regions.

We have a demo day on July 25th, so it would be great if we could already show some stuff, like integration with openaddresses

**Comment by iandees** [comment]
That'd be great, @barthanssens! Let us know how we can help.

**Comment by barthanssens** [comment]
Thanks @iandees, we've created a first set of CSV files and a PR (https://github.com/openaddresses/openaddresses/pull/4582)

I do have a question: can the same CSV be used for  _partially_ translated addresses ?

For the Brussels-Capital Region it is quite easy (even mentioned in the docs as an example, thank you !) because everything is always available in 2 languages.
But in the Flemish and Walloon Region, the vast majority is in 1 language, _with the exception of a few municipalities_ (due to historical/political reasons) that do provide official translations in another language (see also https://en.wikipedia.org/wiki/Municipalities_with_language_facilities)

Now the question is: would it be a problem if we use the same CSV file with separate columns per language + separate metadata JSON files per language, just like Brussels, even if that means that in the vast majority of rows there will be no "second" language (= lot of empty cells for e.g street names) ?

Or should we create an additional CSV file per region, with these exceptions (= avoiding to have empty cells) ?

**Comment by iandees** [comment]
Hmm, that's a good question. I'd say that using the same file is fine for now.

**Comment by barthanssens** [comment]
Thanks, we'll do that.

Another question if I may, is there an attribute to indicate parts of a city ?

Many small villages merged into larger municipalities in the 70s, but quite a few people still use the names of these villages, while others use the new names...   (yes, we love to make things complicated in .be)

**Comment by barthanssens** [comment]
I'd suggest to close this issue, since the official sources are merged and have been used for quite some time (see http://results.openaddresses.io/sources/be/vlg/bosa-region-flanders-nl)

**Comment by iandees** [comment]
👏
