### ISSUE TITLE
Dubai Address Data

### ISSUE THREAD

**Issue by mmb436** [openaddresses/openaddresses#3021]
I reached out to the GIS unit at Dubai Municipality for address data, and they said that their Makani address data is open and free to use, and sent me this link:
http://login.dm.gov.ae/wps/portal/opendata?urile=wcm:path:/DMContentEnglish/Home/OpenData/Makani&mapping=opendata

I need help figuring out how to download the actual address data. There are some instructions here:
http://login.dm.gov.ae/wps/wcm/connect/b1c96c7e-98d3-447a-b4b4-6c84f15e027a/Makani+Public+Web+Service+Access.pdf?MOD=AJPERES

Can someone please help figure this out?

**Comment by thatdatabaseguy** [comment]
Great find! Have been looking forward to data from Dubai.

Poked around a bit and came across this ESRI layer: http://www.makani.ae/arcgis/rest/services/DMap_EL_2015/MapServer/14. It has ~127k records with Makani codes, which are essentially unique IDs for each building entrance (each Makani has a QR code and is the only piece of information needed to get to practically any location in Dubai, very interesting system). Of those, ~57k have a street name listed. That is, suffice to say: :fire::fire::fire:

For adding into OpenAddresses, we usually separate multilingual sources by language, so there'd be one file for Arabic and one for English (see [Saudi Arabia](https://github.com/openaddresses/openaddresses/tree/master/sources/sa/al-madinah) for an example). I'd recommend mapping Makani to house number, the road name in each language to street, and the community name in each language to district (city would be understood to be Dubai).

If you'd prefer to send the pull request, feel free. Otherwise I can do it.

**Comment by mmb436** [comment]
Thanks. I actually don't know how to convert the files, so if you're OK to do the pull request, that would be great. Thanks again.

**Comment by thatdatabaseguy** [comment]
No problem, just added them in #3026.
