### ISSUE TITLE
au/wa/statewide (Western Australia) Landgate addresses

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#3677]
https://catalogue.data.wa.gov.au/dataset/cadastre-address-lgate-002

@nvkelso or @iandees Can you please look at the license of this before we use? This has a lot of locations that are not in the GNAF.

**Comment by nvkelso** [comment]
There are a lot of words in various flavors there...

**Comment by justinelliotmeyers** [comment]
should I remove the sources tag for this?

**Comment by nvkelso** [comment]
It’s a lower priority since we already have an Australia source… Same thing
for the Mass. data.

**Comment by andrewharvey** [comment]
Given the licensing on this dataset is for personal non-commercial use, I don't think it's appropriate to include in OpenAddresses "A global collection of address data sources, **open and free to use**."

© Western Australian Land Information Authority (Landgate). Use of Landgate data is subject to [Personal Use License](https://www0.landgate.wa.gov.au/__data/assets/pdf_file/0009/19890/SLIP-Transaction-Personal-Use-Licence.pdf) terms and conditions unless otherwise authorised under approved License terms and conditions.

**Comment by andrewharvey** [comment]
See also #1154

**Comment by justinelliotmeyers** [comment]
no data

**Comment by andrewharvey** [comment]
There is data available here, but it's only per a personal use license https://www0.landgate.wa.gov.au/__data/assets/pdf_file/0009/19890/SLIP-Transaction-Personal-Use-Licence.pdf. OpenAddresses doesn't as far as I can tell have a policy on which licenses are accepted but if the license doesn't even allow OpenAddresses to pubish the data I don't see how it can or should be included. So okay to close this ticket since it's not actionable.

**Comment by justinelliotmeyers** [comment]
@andrewharvey just going back and closing out issues - the backlog is massive and want to sort things out. If we didnt have a nation-wide dataset for AU, I would have kept open and been a bit more involved with communication with their government trying to get approval.  Really appreciate your time and help!!

Justin
