### ISSUE TITLE
Add country as field in schema for individual files

### ISSUE THREAD

**Issue by nishantnath** [openaddresses/openaddresses#3992]
More of a request rather than issue. Adding the country to the csv-files would greatly improve usability.
Right now a postal code could potentially exist in multiple countries and the way to determine the address belonging to a particular country is more of a dependency on the file/folder structure it came from rather than the file itself

**Comment by andrewharvey** [comment]
@nishantnath do you mean in the collections at http://results.openaddresses.io/ ?

I agree, this can apply at different levels too like state/province for statewide sources.

One way to address this is by adding a static field as an [attribute tag](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-tags) to sources so you can add fixed strings directly rather than coming from the source data.

This would be handy for statewide sources which aren't able to set a fixed `region`.

The other option though is to automatically set a country field in the output CSVs based on the country tag already defined in the `coverage`

**Comment by ingalls** [comment]
I appreciate the feature suggestion.

Since we now have a full API at batch.openaddresses.io that includes country information, I don't see as being something that we add on the per-source level.
