### ISSUE TITLE
us-il-peoria

### ISSUE THREAD

**Issue by jalbertbowden** [openaddresses/openaddresses#473]
Peoria County  
http://www.peoriacounty.org/gis

**Comment by davidchiles** [comment]
Address data here http://gis.peoriacounty.org/arcgis/rest/services/DP/CommunityLayers/MapServer/64
Also need to add `?f=json` to end of url for view in browser.

I need some help with the regex on the `prop_street` field
```js
"conform": {
        "type": "geojson",
        "number": {
            "function": "regexp",
            "field": "prop_street",
            "pattern": "^([0-9]+)"
        },
        "street": {
            "function": "regexp",
            "field": "prop_street",
            "pattern": "^(?:[0-9]+ )(.*)",
            "replace": "$1"
        },
        "city":"CITY",
        "postcode": "PZIP"
    }
```

This isn't great because it gives back street values like `W WILLOW KNOLLS UNIT 82D RD`. The units value is mixed in with the street name and the street type.

**Comment by trescube** [comment]
Wow, that is some messy data.  That's probably as good as it's going to get at least with the `regexp` function (insofar as I understand its abilities).  Could you add `unit` to it yet to grab the ones that are postfixed?
