### ISSUE TITLE
US States missing from collection zipfiles

### ISSUE THREAD

**Issue by Atomahawk** [openaddresses/openaddresses#5740]
After running a check against the folder structure, the following states are missing from the zipfiles:

- [x] HI Hawaii
- [x] MO Missouri
- [x] NJ New Jersey
- [x] NY New York
- [x] PA Pennsylvania

Territories are also not given folders in the folder structure:

- AS American Samoa
- GU Guam
- MP Northern Mariana Is
- PR Puerto Rico
- VI Virgin Islands

Also odd that the us-northeast zip file is significantly smaller than other US regions.  Is this expected behavior?

**Comment by ingalls** [comment]
Hey @Atomahawk, thanks for reporting. This is not the expected behaviour - I've identified the problem and am working on a fix. Will update here once this is resolved

**Comment by ingalls** [comment]
The precursor to fixing this has now been merged: https://github.com/openaddresses/batch/pull/168

- [ ] Use new Collection Edit UI to add missing states
- [ ] Kick off a new collection run

**Comment by ingalls** [comment]
As to to the remaining country codes, I strictly follow the ISO 8166-Alpha2 designations to avoid "worldview" debates at this time. If an ISO 8166-Alpha 2 code exists for what some would view as a "region", we typically manage it as a country. 

So places such as Guam, Taiwan, or American Samoa would be managed as a top level region instead of a sub-district. If you find places where this policy is not consistent feel free to open a ticket and I'll get it corrected. 

Thanks again for opening this issue. My migration script from the original server missed these regions. It's good to get them corrected.
