### ISSUE TITLE
More recent batch available for Finland than included in /api/data

### ISSUE THREAD

**Issue by mapbox-danny** [openaddresses/openaddresses#5793]
It looks like a more recent batch has been processed for Finland than is available from:
https://batch.openaddresses.io/api/data

It is currently returning the 6/11/2021 batch: {"id":643,"fabric":false,"source":"fi/countrywide-fi","updated":"2021-06-11T12:36:30.438Z","layer":"addresses","name":"country","job":115128,"output":{"cache":true,"output":true,"preview":true}

However, the most recent processing of Finland source was completed (including the recent correction) on 06/18/2021:
https://batch.openaddresses.io/job/117973

Is there a way to automatically have /api/data return the latest successful batch? Is that the expected behavior?

**Comment by ingalls** [comment]
@mapbox-danny I've diagnosed root cause which appears to be the memcached server which alleviates load (and significantly increases response time) from the core DB.

It appears as though the data in memcached is not being invalidated properly on a new source run. Defeating the memcached layer by filtering by a specific source returns the new data as expected `https://batch.openaddresses.io/api/data?source=fi/countrywide`

I'll investigate why the invalidation is not taking place and get a fix pushed.

**Comment by ingalls** [comment]
The latest data should now be present in the `/data` endpoint
