### ISSUE TITLE
github page for process

### ISSUE THREAD

**Issue by justinelliotmeyers** [openaddresses/openaddresses#6060]
Hey! Sorry this is most likely not the best place to ask this, but where is the main repo for where OA does its magic? IE pulling sources - checking counts, flagging source counts that went to zero or services are no longer live, etc?

I am trying to understand where the magic happens and what that code actually looks like. How often services are pinged and if the first query errors, how/ when it is attempted a second time. 

Thanks!
ATTN @iandees or @ingalls

**Comment by ingalls** [comment]
@justinelliotmeyers I'm afraid there are three different places where this is performed. 

Batch-Machine performs the initial pull from the service: https://github.com/openaddresses/batch-machine
Batch/task performs the processing into a GeoJSON: https://github.com/openaddresses/batch
Batch/api performs the actual serving & stats: ttps://github.com/openaddresses/batch

The services are pinged weekly and if they fail they are not re-queried until the next week. The source ends up in the Job Error log at batch.openaddresses.io and the logs are retained for a week or two so that a human reviewer can see if they can figure out why it fails/how to fix it. 

Let me know if you have a more specific thing you want to know about!

**Comment by justinelliotmeyers** [comment]
@ingalls This is perfect for now - I will have no idea exactly what I am looking at but it is what I need to look at.

Appreciate it!!
Justin
