### ISSUE TITLE
How are we supposed to contribute?

### ISSUE THREAD

**Issue by tomaz-suller** [openaddresses/openaddresses#7085]
Some issues have been open for almost a decade already, including my #6066 which I  opened two years ago to no reply.

I'd like to contribute with data from the latest Brazilain census, but not if my issue or PR only sits unanswered for years.

**Comment by iandees** [comment]
Hi! This is a good question, thanks for asking.

Normally, most contributions happen by creating a pull request to point to an existing, publicly available dataset in a common format (e.g. an Esri MapServer endpoint or a GeoJSON file at a URL). If you look at the recent pull requests those are the ones that are most common.

Your PR has stagnated because we don't normally want to use data that we generate ourselves. We aren't set up to run these custom extraction scripts on OpenAddresses infrastructure.

Also it just got overlooked, so I appreciate the nudge. I'll take a look and offer feedback over on your pull request.

**Comment by tomaz-suller** [comment]
Alright, I also understand your point about running third-party code for long (downloading BR data took me almost 6h last time I tried).

Still, in the case of Brazil for instance, where we the government office just provides us with literally CSVs, would there still be a way to contribute?

I thought about writing the script as well honestly because that's what the `/sources/br` directory had at the time, but I see things have changed since then.

Thanks!

**Comment by tomaz-suller** [comment]
Side comment (ignore as you wish): when I see so many issues and PRs open like that, I question if the project is actively maintained. In my case I thought about contributing earlier and just forgot because of this reason.

But like I said at the beginning, I'm by no means the maintainer nor have any experience with open data, so my opinion is worth just as much as anyone else's (and definitely a lot less than you guys').

**Comment by iandees** [comment]
> in the case of Brazil for instance, where we the government office just provides us with literally CSVs, would there still be a way to contribute?

You can run the script to generate the updated data and then ask to upload it to our S3 bucket and we can use that as a URL for a source update.

> when I see so many issues and PRs open like that, I question if the project is actively maintained. In my case I thought about contributing earlier and just forgot because of this reason.

I think a better metric of understanding how active a project is is to look at merged pull requests. From that perspective, this repo has seen activity, even if there are open issues and pull requests. Some repositories use these tools in different ways. We keep some issues open on purpose because there's a ton of work to do.

Anyway, thanks for asking the question. I encourage you to run the script to get an updated output that we can use and update the data.
