### ISSUE TITLE
Possible incorrect mapping for NZ data

### ISSUE THREAD

**Issue by mtravis** [openaddresses/openaddresses#7257]
Hi there

Just taking a look at the [NZ countrywide.json](https://github.com/openaddresses/openaddresses/blob/master/sources/nz/countrywide.json#L43-L44) and it struck me that the mappings for don't seem quite right. 

```
"city": "suburb_locality",
"district": "town_city", 
```

If you query the data you see something like this

` 'number': 75A, 'street': McElwee Street, 'unit': , 'city': Jervoistown, 'district': Napier,`

but in the source data it's the other way around? 

![image](https://github.com/openaddresses/openaddresses/assets/1799238/f6c633b8-b02d-4d5b-8af9-2d7a5a7964a2)

@andrewharvey  I'm assuming this could be intentional so the suburbs level is captured? Is this common elsewhere in OA schemas?

**Comment by hamishcampbell** [comment]
Hi there,

Not an expert but familar with the sources. Will ask others to verify, but:

Given the hierarchy of addresses, the current configuration for city/disctrict looks **correct**. We essentially don't use the "distrcit" (or territorial authority) for addressing purposes, and the data is structured such that `suburb_locality` + `town_city` will give an addressable location, dispite the apparent mismatch. (e.g. from the example above Jervoistown is a suburb of the city of Naper).

The source data used above is the "NZ Street Address" dataset, which was superceded in Jan 2023 by the "NZ Addresses" data available at https://data.linz.govt.nz/layer/105689-nz-addresses/ - it looks like the reference to layer ID 53353 needs ot be updated to 105689. The linked data dictionary at https://data.linz.govt.nz/document/24489-nz-addresses-data-dictionary/view/ describes how it should be used.

Note that it includes full address examples. It looks like `full_address_number` can be used in place of the existing `number` definition (since it is "All number components concatenated for an address").

**Comment by andrewharvey** [comment]
@mtravis I think to be consistent with other global sources within OA, the NZ "town_city" field should be mapped to the OA "city" field, however OA doesn't have a field corresponding to the NZ "suburb_locality" and since this field is essential for addressing in NZ, bumping the NZ "town_city" up to the OA "district" to leave space for the NZ "suburb_locality" in the OA "city" field as in the current schema mapping is the best solution we have.

The hierarchy order of both the NZ data (`suburb_locality`, `town_city`) and OA (`city`, `district`, `region`) must be retained with the mapping we use.

I suspect the reason OpenAddresses doesn't have a sub-city field is due to the US roots of the project where suburb/locality doesn't form part of the address.

Take this example 4542 Irving St, San Francisco, CA 94122, United States

![image](https://github.com/openaddresses/openaddresses/assets/117278/970badd7-48c9-4b5c-99ab-322dc4b8afcb)

Although within "Outer Sunset" that it's not represented in the address.

Note that the same applies to the AU sources, where we map suburb/locality into the "city" field, and at least in the AU case the actual city (eg. San Francisco) doesn't form part of the address at all.

**Comment by andrewharvey** [comment]
> The source data used above is the "NZ Street Address" dataset, which was superceded in Jan 2023 by the "NZ Addresses" data available at https://data.linz.govt.nz/layer/105689-nz-addresses/ - it looks like the reference to layer ID 53353 needs to be updated to 105689. The linked data dictionary at https://data.linz.govt.nz/document/24489-nz-addresses-data-dictionary/view/ describes how it should be used.
> 
> Note that it includes full address examples. It looks like full_address_number can be used in place of the existing number definition (since it is "All number components concatenated for an address").

Thanks @hamishcampbell I can fix that.

**Comment by dwsilk** [comment]
Interesting that OA doesn't have a "sub-city" field.

I agree with @hamishcampbell and @andrewharvey's comments, and I work for Land Information New Zealand.

**Comment by iandees** [comment]
In the US the sub-city/neighborhood/suburb is mostly made up (usually by realtors or developers) and subjective/changes over time, so it's not used as part of addressing (even informally).

We could definitely consider adding a field that represents this in the output schema for OpenAddresses, especially if it's an important part of addressing elsewhere.

**Comment by andrewharvey** [comment]
> Note that it includes full address examples. It looks like full_address_number can be used in place of the existing number definition (since it is "All number components concatenated for an address").

@hamishcampbell The `full_address_number` includes both the address and unit, which OA provides separate fields for, so we either split full_address_number into the parts, or continue to reconstruct the unit and number fields from the sources.

Given this I wanted to validate the mapping so in QGIS I created a new field with expression

```
if("unit_value" != '', "unit_value" || '/', '') ||
"address_number_prefix" ||
"address_number" ||
"address_number_suffix" ||
if(
   "address_number_high" != '',
   '-' || "address_number_prefix" || "address_number_high"  || "address_number_suffix",
   ''
)
```

Then compared those values against `full_address_number` and found it always matched, so that's good.

In search of edge cases I found "1A-7A Puka Place, Inglewood" which shows the suffix applying to both the low and high number parts, which is something the current mapping we use gets wrong as OA will format it as "1A-7"

**Comment by hamishcampbell** [comment]
By the way, it looks like it's been a while since the NZ addressing data was updated. What's the usual frequency?

**Comment by andrewharvey** [comment]
> By the way, it looks like it's been a while since the NZ addressing data was updated. What's the usual frequency?

It should be weekly, but thhe OA data has been stuck at November 2022 due to the reason you mentioned. I have a PR which updates this as you suggested.

> The source data used above is the "NZ Street Address" dataset, which was superceded in Jan 2023 by the "NZ Addresses" data available at https://data.linz.govt.nz/layer/105689-nz-addresses/
