### ISSUE TITLE
us-md

### ISSUE THREAD

**Issue by tritania** [openaddresses/openaddresses#726]
[Link](http://data.imap.maryland.gov/datasets/20878dd2c20949a8a14a5a282ab98807_0?geometry=-77.734%2C39.003%2C-76.416%2C39.323) contains data for the entire state of Maryland.

**Comment by slibby** [comment]
I believe this can be closed due to https://github.com/openaddresses/openaddresses/blob/master/sources/us/md/statewide.json

**Comment by talllguy** [comment]
The statewide data referenced by @slibby and @geobrando in https://github.com/openaddresses/openaddresses/issues/726#issuecomment-150349696 represents parcel points, not address points.

For this project is is it worth making a distinction?

**Comment by slibby** [comment]
Yes, definitely want a distinction, but I am not aware of a statewide point address dataset (yet) -- is there one you know of? If so, it would supersede the parcel-based dataset (as long as the total number of valid addresses is similar).

The original link is broken in this issue, so I'm not sure what it was pointing to, my interest in closing it was just general issue tidiness since the dataset wasn't available anymore anyways. I know you're local, so feel free to guide on it.

**Comment by talllguy** [comment]
There is a statewide address point layer, but it is not public. Maryland's state government is very much an open data proponent, but there are certain counties that are not ready to give away this data, thus the state cannot publish it. I will update this issue if there are any updates on the matter of statewide address points.

In the meantime, there are certain counties that publish their data outside of the state umbrella, which tend to be of better quality. Would those datasets be worth referencing?

**Comment by iandees** [comment]
Yup! There's no problem with including both the local county data and the statewide layer.
