### ISSUE TITLE
Pull in SimpleGeo 20m address dump

### ISSUE THREAD

**Issue by petewarden** [openaddresses/openaddresses#806]
From a Twitter discussion with @migurski, I thought the 2011 SimpleGeo 20m address dump might be a useful addition since it's CC0 and not too old:
http://readwrite.com/2011/04/21/facts_should_be_free_simplegeo_puts_20_million_pla

SimpleGeo went out of business so the original links don't work, but I know I've had the files in the past and they may still be on one of my servers. If not, I'll talk to Tyler Bell at Factual since I know he was involved in the original release, and we can ask around other open geo geeks too.

From memory there's worldwide coverage, mostly businesses I believe.

**Comment by migurski** [comment]
:+1:

**Comment by petewarden** [comment]
Aha, it looks like archive.org has what we need:
https://archive.org/details/2011-08-SimpleGeo-CC0-Public-Spaces

I'm downloading it now, and I'll look through the contributors guide to understand what we'll need to do to get it added.

**Comment by petewarden** [comment]
Here's what I've gathered about the layout of the files and data:

The files are in a .zip archive, broken out by country and named with two-letter codes, and are also individually gzipped, so places_dump_SE.geojson.gz is the Swedish address file.

Internally, each file has one GeoJSON object per line, so running this:
`gunzip -k -c ~/Downloads/places_dump_20110628/places_dump_SE.geojson.gz | head -n 1`

gives

`{"geometry": {"type": "Point", "coordinates": [18.077451, 59.336527]}, "type": "Feature", "id": "SG_6uCQnsEzU6rB0HN8cAqHiy_59.336527_18.077451@1308163237", "properties": {"website": "http://www.xindesk.com", "city": "Stockholm", "name": "Xindesk", "tags": ["sweden", "webos", "webtop"], "country": "SE", "classifiers": [{"category": "Professional", "type": "Services", "subcategory": "Computer Services"}], "href": "http://api.simplegeo.com/1.0/features/SG_6uCQnsEzU6rB0HN8cAqHiy_59.336527_18.077451@1308163237.json", "address": "Majorsgatan 4", "owner": "simplegeo", "postcode": "113 24"}}`

I see GeoJSON is supported by OpenAddresses, so hopefully we can pull these in fairly easily?

**Comment by sbma44** [comment]
The two layers of compression mean that some reorganization will probably
be necessary. But since these files are orphaned, there's no real downside
to doing this rather than using a canonical source.

I'd suggest splitting the files out into individual sources. From the
excerpt you've posted I think it should be pretty easy to get this into
shape once the archives are reorganized.

Oh: also note that we've been using zip rather than tar (for reasons I'm
not 100% clear on).

**Comment by twbell** [comment]
Been a while since we (Factual) looked at this file Pete.  Was not current when exported and we ended up using nothing that was not verified by multiple other sources.  That being said, most of the issues were with the business categorization rather than the address validation, so should be a good, if skeptical, resource for this purpose.

**Comment by iandees** [comment]
I'm going to close this because OpenAddresses prefers to use data from primary sources (like city, county, and state governments). If someone wants to take on reorganizing the data from SimpleGeo we can reopen and discuss again.

**Comment by nvkelso** [comment]
This could be scraped from Who's On First venues (which is SimpleGeo reborn)... But their addresses are generally street interpolation so agree with Ian.
