### ISSUE TITLE
Esri Open data portal

### ISSUE THREAD

**Issue by geobrando** [openaddresses/openaddresses#889]
I just created a pull request in #888 for a shapefile source I found using the [Esri Open Data Portal](http://opendata.arcgis.com/).  The site is now fully operational and allows for download of data in csv, KML, and shapefile formats, as well as provides urls for a GeoJSON or GeoService API.  Most of these appear to be converted on the fly from Esri servers hosted by the different municipalities.

My questions are:
1. What would be the preferred format when submitting a source from the portal?
2. I know that there have been issues previously with pulling addresses from Esri servers.  It was stated in #336 that shapefiles are preferred over Esri servers.  Is there any benefit to changing our existing sources from Esri to shapefiles or another format?
3. The shapefile from the source I submitted was named `e946260f3b23471fa0e3657034bac382_0.zip`.  I don't how their process for generating these names.  Do you think there's any reason to believe that the `data` urls might not be stable over time?

**Comment by migurski** [comment]
There may be a benefit to switching; Esri Feature JSON sources require a time-consuming crawl of address points, while shapefile downloads are a single download. It's better to have one URL 404 when debugging, than to chase an error through hundreds of requests.

Unsure about the data URL stability. Give it a shot, we'll see what happens. We do cache data over time, so an unstable URL won't eject data from http://data.openaddresses.io/

**Comment by iandees** [comment]
We should definitely take advantage of Shapefile downloads from opendata.arcgis.com, but I'm pretty sure that they're only going to include data sources that are already on arcgisonline.com. Most of our existing ESRI sources are not using arcgisonline.com, they run their own ESRI servers on their own hardware. Unless I'm mistaken, I don't think opendata.arcgis.com will help us in those cases.

**Comment by geobrando** [comment]
@iandees There's some overlap. The portal exposes all data from orgs that have the ```open data``` button turned on, whether hosted on ArcGIS Online or on their own Esri servers.

**Comment by geobrando** [comment]
Found a fatal flaw in my plan to add Esri Open Data sources to the current processing pipeline. It's clear that this initiative is not as "open" as I'd previously thought, as the site was designed for a multi-step process using a download console in the browser.

As mentioned, the portal exposes feature service data hosted on either private Esri servers or directly on http://opendata.argcis.com.  Shapefiles, kmz, spreadsheets, etc are generated by some middleware and cached.

A request to urls linked from "Shapefile" will return the static resource if it's in the cache.  Not sure how long they remain cached.  If not, it returns a 202 status and a json with something like the following and closes the connection:

```json
{"status":"processing","processing_time":0,"count":0}
```
While the resource is being generated, subsequent requests return something like one of the following:
```json
{"status":"processing","processing_time":24.35,"count":37152}
{"status":"processing","processing_time":651.657,"count":251245,"generating":{"progress":"0%"}}
```
Only when the resource has been generated and cached will it be returned.  This may take a few seconds, or several minutes depending on the feature server and the size of the dataset.

So we should avoid adding these sources until we decide on how to deal with this.  I'm a novice, but could it be as simple as using [setInterval()](http://nodejs.org/api/timers.html#timers_setinterval_callback_delay_arg)

**Comment by jalbertbowden** [comment]
i concur they're not as open as it seems....i'm not positive, but i believe you found why over half of the time i try to download data from esri portals, i get empty zip files. it is wicked annoying.

**Comment by NelsonMinar** [comment]
openaddresses-machine could handle this kind of download with Python code. Trigger the generation and then keep checking the status JSON blob until it's ready to download. The way machine works now it won't be very efficient (tying up a worker thread) but probably better for all concerned than scraping the ESRI endpoint. We could also make it more efficient if necessary.

**Comment by geobrando** [comment]
@ajturner  Is Koop the middleware used in the Open Data portal?

**Comment by ajturner** [comment]
Thanks for the feedback. I agree this is annoying - let me explain why that's the case now, how we're improving that and open for suggestions to make it easier.

First, we generate the files at request time so it is always the most recent version of the data. We check if our cached version is newer then last edit date - if so file is immediate. If the data are newer, then we bake a fresh download. This requires time to page and get all the data to then put into a zipped shape file. The HTTP header says 202 which is intended to say generating and continue checking. 

Is there a better (more open) way to tell the worker "we're getting you the most recent data, please hold"?

Our next phase is to allow the data owner to specify how often the cache should be updated. We will then generate the download per their schedule - or if they so choose, leave it automatic per the logic above.

Last, we are generating versioned files - but don't currently expose them. There is a lot of concern from agencies that data are stale and used incorrectly.

All that said, what would you want to see? We are building this to be as open and useable as possible; while also serving as up to date data as possible. Shapefiles and any bulk format is a necessity, but also a problem. 

@geobrando  per your question - yes. Koop is the middleware here, and handles all the pagination logic. Since [Koop is open-source](https://github.com/esri/koop) you can look at the code and convert to Python or re-use the Koop-AGOL JavaScript implementation.

**Comment by ingalls** [comment]
Closing as stale, ESRI open data portals are now super common :)
